version: "3.8"

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
  origin:
    image: node:16.15-alpine
    volumes:
      - ./origin:/image-list
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HOST: 0.0.0.0
    working_dir:  '/image-list'
    command:
      node server/index.mjs
    ports:
      - 8888:8888